#!/bin/bash

set -eu

_help() {
  cat ./help.txt
}

_extract() {
  TMP_DIR="$(mktemp -d)"
  cp "$1" "$TMP_DIR/EXTRACT_MEDIA_TMP.zip"
  unzip "$TMP_DIR/EXTRACT_MEDIA_TMP.zip" -d "$TMP_DIR/out" > /dev/null

  MEDIA_FILES="$(find "$TMP_DIR/out" \( -name "*.png" -o -name "*.jpg" -o -name "*.mp4" -o -name "*.gif" \))"

  if [ "$MEDIA_FILES" == "" ]; then
    echo "No media found."
  else
    MEDIA_NB=0
    while read -r line; do
      MEDIA_NB=$((MEDIA_NB+1))
      cp "$line" "$2/"
    done <<< "$MEDIA_FILES"
    echo "$MEDIA_NB media succesfully extracted to $2"
  fi
}

if [ $# -eq 0 ]; then
  echo "Please define the file you want to extract media from."
  _help
  exit
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  _help
  exit 1
fi

# Check the availability of unzip
if ! command -v unzip &> /dev/null; then
  echo "Please install the unzip binary."
  exit 1
fi

if [[ $1 == *".key" ]] || [[ $1 == *".docx" ]]; then
  FILE_PATH="$1"
  DESTINATION=${2:-$PWD/}

  # support relative and absolute file paths
  if [[ "$FILE_PATH" != /* ]]; then
    FILE_PATH="$PWD/$FILE_PATH"
  fi

  # make sure the destination path ends with a "/""
  [[ "${DESTINATION}" != */ ]] && DESTINATION="${DESTINATION}/"

  _extract "$FILE_PATH" "$DESTINATION"
else
  echo "Extract media only supports .key and .docx file formats."
  exit 1
fi
